FROM ubuntu:18.04

WORKDIR /src
ADD . .

RUN apt-get update && \
    apt-get -y install git gnupg curl software-properties-common

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

RUN add-apt-repository -y ppa:jonathonf/ffmpeg-4 && \
    apt-get install -y nodejs ffmpeg

RUN npm install && \
    apt-get -y remove git && \
    npm install

EXPOSE 5000

CMD ["node", "app.js"]