apiVersion: v1
kind: Service
metadata:
  name: sentinel-rtsp-bridge
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rtsp-bridge
    context: sentinel
    version: v1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rtsp-datastore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-rtsp-bridge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rtsp-bridge
        context: sentinel
        version: v1
    spec:
      volumes:
      - name: rtsp-storage
        persistentVolumeClaim:
          claimName: rtsp-datastore
      containers:
        -
          name: sentinel-rtsp-bridge
          image: docker.steventaylor.me/sentinel/rtsp-bridge/rtsp-bridge-x86_64:latest
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          - name: CONSUL
            value: "consul"
          - name: STORAGE_PATH
            value: "/data"
          ports:
            -
              containerPort: 5000
              protocol: TCP
          volumeMounts:
          - mountPath: "/data"
            name: rtsp-storage
      imagePullSecrets:
      - name: regcred
      nodeSelector:
          beta.kubernetes.io/arch: amd64